machine:
  services:
  - docker
  ruby:
    version: 2.3.0

dependencies:
  override:
  - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3:
      timeout: 900

test:
  override:
  - bundle exec kitchen test:
      timeout: 900
